@startuml SequenceDiagram Login


actor User
participant "Database Manager"
database "Database"
activate "Database Manager"

User -> "Database Manager" : addToDiary(Title, Date)

"Database Manager" -> Database : QueryDatabase(Title, Date)
activate "Database"

alt If diary is in acceptable format
"Database" --> "Database Manager" :  AddToDatabase(DiaryInfo)
deactivate "Database"
"Database Manager" -> User : "Diary Saved"
deactivate "Database Manager"


else If diary is in unacceptable format
"Database" -> "Database Manager" : Error saving Diary
"Database Manager" --> User : "Error diary not saved"

else If diary is null
"Database" -> "Database Manager" : Error saving Diary
"Database Manager" --> User : "Error diary not saved"


end
@enduml